version: 2.1

orbs:
  architect: giantswarm/architect@8.3.0

workflows:
  test:
    jobs:
      - architect/go-build:
          context: architect
          name: go-build
          binary: team-stamper
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          split-china-push: true
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
                - main

      - architect/sync-china-registry:
            context: architect
            name: sync-china-registry
            requires:
              - go-build
              - push-to-registries
            filters:
              tags:
                only: /^v.*/
              #branches:
                #ignore: /^.*$/

      - architect/push-to-app-catalog:
          context: architect
          executor: app-build-suite
          name: push-to-app-catalog
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          chart: team-stamper
          persist_chart_archive: true
          requires:
            - push-to-registries
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
              - main

      - architect/integration-test:
          context: architect
          kubernetes-version: v1.35.1
          name: e2e-tests
          setup-script: config/setup.sh
          test-dir: tests/integration
          requires:
            - go-build
            - push-to-app-catalog
          # we do not push to registries from the 'main', see above,
          # hence we cannot test from the 'main', in general. That is we
          # could do it by loading an image we build anyway into KinD,
          # but since all the work flows through PRs and branches,
          # the tests are run for them, so it anyway feels redundand
          # to run them in 'main' too after merging.
          filters:
            branches:
              ignore:
                - main
